### ISSUE TITLE
This model repeats only same motion when chair is about to stand!

### ISSUE THREAD

**Issue by eyeducky** [shin0805/Chair-TypeAsymmetricalTripedalRobot#1]
Hello, I am interested  in your project and I am trying to make this model "chair". but when I run 'connect_stand.py', no matter how and where chair falls, this chair repeats only same behavior. so could you inspect whether or not model file uploaded in github is same with your model file uploaded in your video? 

PS. if that two file is different is true, could I say can you give me your file that is uploaded in video ?

Thank you.

**Comment by shin0805** [comment]
Thank you for your interest and for taking the time to create the model!

The script `connect_stand.py` executes a pre-designed recovery motion rather than a learned behavior. 
If you want to perform a recovery motion based on reinforcement learning, please run `rl_stand.py` instead.
 However, please be cautious as the model can be fragile.

**Comment by eyeducky** [comment]
Thank you for your reply. And I'm sorry for the late confirmation

I was confused because ```Connect_stand.py``` also had code for loading the model file. 
Actually, when I run ```rl_stand.py```, it act recovery motion.  And I saw the possibility of trying to stand for sure.

However this didn't do the right thing because there was a problem with the orientation axis, Because I was have some issues, so I'm using bno08x now.

So, I need to compare the axis. Therefore, may I ask why you added '-'(subtraction) to the x and y values ​​of ```imu_msg``` in the python file?
